### ISSUE TITLE
corrupting SSO URL

### ISSUE THREAD

**Issue by rajashekar545** [FormidableLabs/react-native-app-auth#109]
Dear Team , 

We are passing parameters like below 
issuer: 'https://*******/secure/oauth2/authorize?response_type=code&acr_values=usernamepassword_chain_persistent&realm=/TRA',
  clientId: '***',
  redirectUrl: '*****',
  scopes: ['openid', 'email']

when its opening SSO url in browser , its opening as that's its adding '/TRA' in the URL.
https://*******/secure/oauth2/TRA/authorize?response_type=code&acr_values=usernamepassword_chain_persistent

Kindly help us to over come this .

Thanks and Regards
Rajashekar Reddy Ette

**Comment by kadikraman** [comment]
Hi 👋  - sorry for the delay in replying to this. I hope you managed to resolve your problem. The issuer url shouldn't include any url arguments as they are added automatically by the library, which is why I imagine the was causing the issue.

I'm closing this, but please feel free to create another issue if your problem persists.
