### ISSUE TITLE
Library does not work when using Expo's create-react-native-app

### ISSUE THREAD

**Issue by sam-warren** [FormidableLabs/react-native-app-auth#115]
When initializing a react-native project with create-react-native-app, user will always get an "Undefined is not an object (evaluading foo.authorize)". Often times this issue was due to RNAppAuth being undefined in index.js. Please fix!

**Comment by kadikraman** [comment]
Unfortunately, because the setup for this library includes adding some native code, it can only be used on a react native project that has been created via `react-native init` or potentially an expo project that has been ejected. It will be impossible to make it work on an unejected expo project.

In better news, Expo actually comes with AppAuth already built in. The API is slightly different than ours, but [here are some docs for it ](https://docs.expo.io/versions/latest/sdk/auth-session#example).

Disclaimer: I've never used the Expo version, I just know it exists.

**Comment by sam-warren** [comment]
Thank you!
