### ISSUE TITLE
'OIDAuthorizationFlowSession' is deprecated: Use the more generic OIDExternalUserAgentSession instead.

### ISSUE THREAD

**Issue by getaaron** [FormidableLabs/react-native-app-auth#156]
This warning appears in the app delegate:

![image](https://user-images.githubusercontent.com/789577/43600486-afcce934-9658-11e8-9618-89c952b31b19.png)

This recommendation is maintained in the README, most recently in https://github.com/FormidableLabs/react-native-app-auth/commit/dd8dd75f16b682f5f46c7169815622e8f1207ee4

**Comment by cherylbearden** [comment]
I also got this error related to OIDAuthorizationFlowSession.. .see issue 159: 

Unknown class name 'OIDAuthorizationFlowSession'; did you mean 'OIDAuthorizationService'?
Replace 'OIDAuthorizationFlowSession' with 'OIDAuthorizationService'

**Comment by styk-tv** [comment]
I also got this error related to OIDExternalUserAgentSession in 3.1.0

<img width="792" alt="screen shot 2018-08-24 at 08 29 22" src="https://user-images.githubusercontent.com/838921/44571287-43310400-a778-11e8-9b2b-fb243bb84010.png">

**Comment by kadikraman** [comment]
@styk-tv I think your issue is most likely due to not adding the native code specified [here](https://github.com/FormidableLabs/react-native-app-auth/#define-openurl-callback-in-appdelegate)

@getaaron sorry for the late reply, I think the latest release has resolved that issue (the iOS instructions have changed quite a bit but are much simpler now)

Closing this, please reopen/create a new issue if this problem persists 🙌

**Comment by styk-tv** [comment]
It was right after the release of new version and documentation was pointing to a commit id of a previous version. Once I found out it was fixed and updated, it worked fine. Thanks.
