### ISSUE TITLE
Identity Server 3.0

### ISSUE THREAD

**Issue by tienw** [FormidableLabs/react-native-app-auth#19]
Before I try on IdentityServer 3, do you know this supports 3.0 or not?

Thank you

**Comment by brockallen** [comment]
IdentityServer3 supports the OIDC and OAuth2 protocols. As long as the library and token servers are both compatible, then they should work. For reference: https://openid.net/certification/

**Comment by kadikraman** [comment]
Indeed, as @brockallen said, the library should work with any provider if they've implemented the OAuth2 spec and have the [discovery endpoint](https://openid.net/specs/openid-connect-discovery-1_0.html) enabled.

We've mentioned Google and IdentityServer 4 in particular just because we have confirmed the library definitely works with them.

If you do end up using the library with IdentityServer 3, it would be really helpful to have it confirmed so we could add it to the readme :)
