### ISSUE TITLE
client_id is not passed in the token exchange request

### ISSUE THREAD

**Issue by palashjhabak** [FormidableLabs/react-native-app-auth#264]
## Issue

client_id id is not passed to the token end point along with other parameters and due of which the token exchange request is failing. 

---

## Environment

- **Frappe**: `e.g. IdentityServer 4 / Okta / Azure`
- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native

**Comment by kadikraman** [comment]
Hi. Which IDP are you using? It _should_ be added to the token request, but you could try also adding it to `additionalParameters` to check.

**Comment by fgagno** [comment]
Hi. @kadikraman, I had the same problem with my rails app and Google sign-in, so I tried to add it to additionalParameters, and now it's passed.
I shouldn't need to do so, but it works. 
Thanks.

**Comment by bhaskardabhi-oviyum** [comment]
I tried adding in `additionalParameters`. It didn't work for me.

```
config = {
    clientId: "{clientId}",
    clientSecret: "{clientSecret}",
    redirectUrl: "{redirectUrl}",
    serviceConfiguration: {
      authorizationEndpoint: "https://www.strava.com/oauth/mobile/authorize",
      tokenEndpoint: "https://www.strava.com/oauth/token",
      revocationEndpoint: "https://www.strava.com/oauth/deauthorize"
    },
    additionalParameters: {
      approval_prompt: "force",
      grant_type: "authorization_code",
      client_id: "{client_id}",
      client_secret: "{clientSecret}"
    },
    scopes: ["activity:read"]
  }
```

Let me know if I am doing something wrong here.

**Comment by kadikraman** [comment]
`grant_type`, `client_id` and `client_secret` should all be passed in by the library, since you added them to the config. There should be no need to add them manually. You could try a breakpoint [here](https://github.com/FormidableLabs/react-native-app-auth/blob/master/android/src/main/java/com/rnappauth/RNAppAuthModule.java#L317) to inspect the request, and [here](https://github.com/FormidableLabs/react-native-app-auth/blob/master/android/src/main/java/com/rnappauth/RNAppAuthModule.java#L328) to inspect the underlying error.

**Comment by bhaskardabhi-oviyum** [comment]
I debugged the internal code. I need to pass client_id & client_secret in the request for [Token exchange](https://developers.strava.com/docs/authentication/#token-exchange).

As I am passing clientId & clientSecret, so it going into [this condition](https://github.com/openid/AppAuth-iOS/blob/master/Source/OIDTokenRequest.m#L277) and doesn't send client id which is required by my provider.

So I thought I won't pass `clientSecret` and will mention it as additionalParameters so that 

So I removed `clientSecret` and only sending clientId and pass `client_secret` as an additional parameter so that [this code](https://github.com/openid/AppAuth-iOS/blob/master/Source/OIDTokenRequest.m#L292) will be executed and client id will be passed. As `client_secret` is mentioned in an additional parameter so it will be passed also. But that didn't work as well.

Because [this code](https://github.com/openid/AppAuth-iOS/blob/master/Source/OIDAuthorizationResponse.m#L187) is passing `nil` as the parameter instead of the actual additional parameter. 

I am sure I am doing something stupid. Not sure what is the best way to pass client_id & client_secret as part of the url parameter in token exchange request.

**Comment by kadikraman** [comment]
Thanks for investigating! We're using the convenience method [authStateByPresentingAuthorizationRequest](https://github.com/openid/AppAuth-iOS/blob/b6b5961afa4dc97b6306fb89bb3770e734d397fc/README.md#authorizing-ios) to do the token exchange based on the auth response and it looks like it [does not allow]( https://github.com/openid/AppAuth-iOS/blob/2a7a6754fd5b612aa554fa56d6e7853218e2d84f/Source/OIDAuthState.m#L129) customising the url parameters, so supporting this would require a native change on the iOS side.

**Comment by r0b0t3d** [comment]
I can make it works finally.
You can pass your `client_id` & `client_secret` to `tokenEndpoint` config.
```
const config: AuthConfiguration = {
    serviceConfiguration: {
      authorizationEndpoint: 'https://www.strava.com/oauth/mobile/authorize',
      tokenEndpoint: 'https://www.strava.com/oauth/token?client_id=<your_client_id>&client_secret=<your_client_secret>',
      revocationEndpoint: 'https://www.strava.com/oauth/deauthorize'
    },
}
```

**Comment by cavator** [comment]
ok @r0b0t3d  this worked, but with my callback with is a "<?php ?>" literary is just a empty php file, i have no idea what and HOW redirect back to the app, i already change all need configs, i just don't know how callback

**Comment by r0b0t3d** [comment]
@cavator If you are working with Strava. You have to config `Authorization Callback Domain`. Let's say you set `foo.com`
Then you can pass it to redirectUrl like this
```
const config: AuthConfiguration = {
    serviceConfiguration: {
      authorizationEndpoint: 'https://www.strava.com/oauth/mobile/authorize',
      tokenEndpoint: 'https://www.strava.com/oauth/token?client_id=<your_client_id>&client_secret=<your_client_secret>',
      revocationEndpoint: 'https://www.strava.com/oauth/deauthorize'
    },
    redirectUrl: 'yourapp://foo.com'
}
```

**Comment by danviizr** [comment]
I got stuck for a day or two because of this issue - `clientId` and `clientSecret` were not being passed as expected resulting in an "invalid_client_id" error from Salesforce when trying to obtain a refresh token via the `refresh()` method in react-native-app-auth version 7.1.0 using an Android 13 Pixel 7 Pro.

The workaround that [r0b0t3d](https://github.com/r0b0t3d) provided worked, but if it's possible to fix this issue in the library it could be a big help to others that are using the `refresh()` method in the way shown in the documentation.
