### ISSUE TITLE
Only show iOS authentication dialog once?

### ISSUE THREAD

**Issue by dale-french** [FormidableLabs/react-native-app-auth#274]
Is it possible to only show the IOS redirect notice `{appName} wants to use {provider} to sign in` once / the first time only?

**Comment by kadikraman** [comment]
No, it's not possible. It's caused by `SFAuthenticationSession` and the only way to get rid of it is to not use `SFAuthenticationSession`. See [this issue](https://github.com/openid/AppAuth-iOS/issues/177) on AppAuth-iOS for more details.

**Comment by JoshAntBrown** [comment]
I too am searching for a solution to this problem, and willing to accept the lack of SSO with the Safari web browser on the device in order to achieve this. This requirement seems requested quite often within the AppAuth library, and I came across a number of potential solutions when searching through their GitHub. 

The AppAuth library seems to support the ability to swap out the `SFAuthenticationSession` with another custom defined user agent like `SFSafariViewController` which would prevent this dialog altogether.

The steps for doing so are detailed in: https://github.com/openid/AppAuth-iOS/issues/209#issuecomment-404353236 

Is this extensibility something we could tap into when using react-native-app-auth or is it something we could add into this library to opt-in too perhaps?

**Comment by felri** [comment]
@JoshAntBrown did you find a solution? I'm facing something similar and any help would be appreciated

**Comment by JoshAntBrown** [comment]
@felri  Unfortunately not, felt like we were close but had to move on with what we were doing so currently still have the prompt.

**Comment by christos-z** [comment]
For anyone still stuck on this. I've implemented a patch using patch-package 

https://www.npmjs.com/package/patch-package

Thanks to the work of William Denniss and the gist provided by @JoshAntBrown (https://gist.github.com/WilliamDenniss/18f3779b4a310361bb955cf4e534f29c)

Patch can be downloaded here & automatically applied via patch-package

[react-native-app-auth+6.0.2.patch.zip](https://github.com/FormidableLabs/react-native-app-auth/files/5920323/react-native-app-auth%2B6.0.2.patch.zip)
