### ISSUE TITLE
Keycloak Revoke endpoint not detect with OpenID endpoint configuration

### ISSUE THREAD

**Issue by mnlbox** [FormidableLabs/react-native-app-auth#351]
Hi guys,
Keycloak provide endpoint url's in an endpoint pool like this:
```
<root>/auth/realms/{realm-name}/.well-known/openid-configuration
```
In that list revoke endpoint called `end_session_endpoint` but it seems that react-native-app-auth searching for `revocationEndpoint` or something like this.
I suggest to fix this so we can config my app only by set `issuer` and not all endpoint with `serviceConfiguration` attribute.
Thanks. Now if we only set `issuer` I got this error on revoke:
```
{ [Invariant Violation: The openid config does not specify a revocation endpoint]
```

You can also see this: 
https://www.keycloak.org/docs/latest/securing_apps/index.html#logout-endpoint

---

## Environment

* **Your Identity Provider**: `Keycloak`
* **Platform that you're experiencing the issue on**: `both`
* **Are you using Expo?** NO

**Comment by vovailchenko** [comment]
IMO, you can pass that endpoint manually to the authconfig object:
instead of 
`issuer: '<root>/auth/realms/{realm-name}'`
use
`serviceConfiguration: {
    authorizationEndpoint: 'url',
    tokenEndpoint: 'url',
    revocationEndpoint: 'url'
      }`

i will come across this use-case later, so i may update this issue after i actually try it myslef and am sure it works.

**Comment by kadikraman** [comment]
Hi 👋 - the revocation endpoint is specifically for revoking access tokens, it is _not_ single sign out.

In order to logout, we'd essentially have to implement single sign out. The reason this is tricky is because even though AppAuth iOS has added support for single sign out recently, AppAuth Android does not have support yet, although it is in the backlog.

More discussion about this can be found [here](https://github.com/FormidableLabs/react-native-app-auth/issues/68).
