### ISSUE TITLE
is there any way we could open a webview in the app instead of web browser? (identity server 4)

### ISSUE THREAD

**Issue by blueturtle13g** [FormidableLabs/react-native-app-auth#368]
Thanks for the great work you've done!
for UX purposes we aim to handle the authentication process in the app and not with a browser. so I was looking for a way to achieve this.
like opening a webview in a way that the user doesn't notice it's a webpage. or creating a form in the app and sending the credentials to the URL and get the token without using a  webpage.

**Comment by andresubri** [comment]
The browser is used to avoid the security concerns associated with using a webview. You can find more information in the README

**Comment by kadikraman** [comment]
Hi @blueturtle13g 👋 - @andresubri is correct. We explicitly avoid using WebViews because of the security concerns. You can read more about it in the [AppAuth-iOS](https://github.com/openid/AppAuth-iOS) and [AppAuth-Android](https://github.com/openid/AppAuth-Android) READMEs.

**Comment by Highspeed7** [comment]
I'm appending a comment onto here, because I've came across an issue where on IOS the parameters are being stripped from the url after the app opens the web browser for authentication. First it asks the user if they'd like to navigate away from the app to login... if they hit continue it has then stripped my policy parameter, and it's directed to the generic login screen without applying my signing policy. Is there a solution to this?
