### ISSUE TITLE
Logging in as different user fails

### ISSUE THREAD

**Issue by tensor5** [FormidableLabs/react-native-app-auth#382]
## Issue

My app stores tokens on the device after login, and does logout by clearing device storage. However when I try to login again as a different user, after entering the credentials in the browser instance I get the message

```
You are already authenticated as different user 'foo@bar.com' in this session. Please logout first.
```

Clearing the browser cache solves the problem. Is there anything I'm missing to properly handle logout?

---

## Environment

* **Your Identity Provider**: `Keycloak`
* **Platform that you're experiencing the issue on**: `iOS and Android`
* **Are you using Expo?** No

**Comment by sebleclerc** [comment]
react-native-app-auth exposes only the revoke function which calls the revocation endpoint. This endpoint remove the entry for the user inside the refresh token table. The problem here is that when you login, the identity provident saves some informations inside a cookie. That cookie can only be remove by the identity provider using a logout script. For example, IdentityServer opens a logout window which close right away to do this. I can't say for other provider but this kind of mechanism sure exists. That's why when you clear the cache, it is working because that cookie is cleared. This is all possible using a `end_session_endpoint`.

Now, RN app auth doesn't expose a logout function that would call this endpoint. It wasn't available  in AppAuth iOS until 1.1.0 and not even available in AppAuth Android.

As per the revoke endpoint, RN app auth made a call directly using fetch to the identity provider without using AppAuth because it seems it's not available. Probably it would be something similar to be implemented for the end_session endpoint.

**Comment by tensor5** [comment]
Thank! I have been trying using revoke(), and later found out that [it's not implemented for Keycloak](https://github.com/FormidableLabs/react-native-app-auth/blob/master/docs/config-examples/keycloak.md#keycloak).
 Posting to the `end_session_endpoint` works.

**Comment by expouic** [comment]
@tensor5 can you explain with more details  

> Posting to the end_session_endpoint works.

**Comment by imaginasean** [comment]
Had not attempted to do a direct POST to the end_session_endpoint. Was this
just a direct https call from JavaScript you are referring to?

**Comment by expouic** [comment]
I try to call end_session_endpoint of my keycloak and i have success on logout session.

> http://keycloakhost:keycloakport/auth/realms/{realm}/.well-known/openid-configuration

Change {realm} with your realm configuration and you have the url to execute the fetch.

example:
`http://keycloakhost:keycloakport/auth/realms/{realm}/protocol/openid-connect/logout?id_token_hint=your_keycloak_token
`

**Comment by tensor5** [comment]
Here is what I do

```js
fetch(`${Config.ISSUER}/.well-known/openid-configuration`)
  .then(res => res.json())
  .then(openidConfig => fetch(
    openidConfig.end_session_endpoint,
    {
        body,
        headers: {
            Authorization: `Bearer ${accessToken}`,
            'Content-Type': 'application/x-www-form-urlencoded'
        },
        method: 'POST'
    }
))
```

**Comment by imaginasean** [comment]
Thanks, Nicola, I will test my end session end point out when I have a
chance this week. The caveat, I think, is that this library uses the global
safari instance so if the user was also logged in to web mail (office 365)
this will likely log them out. I confirmed on my iOS device by bringing up
safari and navigating to the Microsoft online site and it knew who I was
after authenticating in the app. Thanks again for your help!

-Sean

**Comment by asiriPiyajanaka** [comment]
> I try to call end_session_endpoint of my keycloak and i have success to logout user.
> 
> > [http://keycloakhost:keycloakport/auth/realms/{realm}/.well-known/openid-configuration](http://keycloakhost:keycloakport/auth/realms/%7Brealm%7D/.well-known/openid-configuration)
> 
> Change {realm} with your realm configuration and you have the url to execute the fetch.
> 
> example:
> `http://keycloakhost:keycloakport/auth/realms/{realm}/protocol/openid-connect/logout?id_token_hint=your_keycloak_token `

This works for me.. thankz...

**Comment by Danushka50** [comment]
> I try to call end_session_endpoint of my keycloak and i have success to logout user.
> 
> > [http://keycloakhost:keycloakport/auth/realms/{realm}/.well-known/openid-configuration](http://keycloakhost:keycloakport/auth/realms/%7Brealm%7D/.well-known/openid-configuration)
> 
> Change {realm} with your realm configuration and you have the url to execute the fetch.
> 
> example:
> `http://keycloakhost:keycloakport/auth/realms/{realm}/protocol/openid-connect/logout?id_token_hint=your_keycloak_token `

Finally worked...Saved my day. Thank you....

**Comment by fuzail-comakeit** [comment]
Hi all. Logout doesn't work and says "Session not active". The above solutions (@expouic , @tensor5 ) are not working on Android because the fetch call for logout is being made inside the App not in the browser instance. I don't see how it can work. If its working for someone please post your solution here

**Comment by yannickpschroeder** [comment]
If you use PKCE your App opens the browser and logs in and saves cookies. When I try to logout calling the end_session_endpoint and try to login at the same Realm with a different user, I get directly logged backed in as the old user, since there is still a valid Cookie saved in this browser tab. Any solutions for that?

**Comment by jspizziri** [comment]
Just wanted to update this thread that [as of 2020 keycloak does support the `revocation_endpoint`](https://github.com/keycloak/keycloak/pull/7106).
