### ISSUE TITLE
Can't navigate to authorization endpoint for Microsoft Azure AD B2C in iOS

### ISSUE THREAD

**Issue by Highspeed7** [FormidableLabs/react-native-app-auth#417]
Please see: https://stackoverflow.com/questions/58897341/oauth2-azure-ad-b2c-parameters-stripped-from-external-web-browser-in-ios for a detailed description of the issue I'm facing as it contains images, etc...

Basically when I try to initiate the authentication flow in iOS it prompts me to continue, once I continue it strips all of the parameters from the URL and takes me to a completely unrelated auth page.

Everything works as expected on Android.

## Environment

* **Your Identity Provider**: `Azure`
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?**: No

**Comment by kadikraman** [comment]
Hi 👋 - looks like the issue is solved in StackOverflow so I hope you managed to solve your problem, but just an FYI for anyone else reading - the issuer should not include any url parameters. These are all added automatically by the library. Any additional parameters you may want to add to the request should be passed in using the `additionalParameters` prop in the config object.

For example:

```js
const config = {
  issuer: "https://some-idp/oauth2",
  additionalParameters: {
    foo: "bar"
  },
 [---]
}
```

will result in `https://some-idp/oauth2?foo=bar`. You don't need to add the `clientId`, `code` etc in the issuer url manually, that is all handled by the library.
