### ISSUE TITLE
RP-Initiated Logout

### ISSUE THREAD

**Issue by DarkSorrow** [FormidableLabs/react-native-app-auth#445]
Hello,

I'm trying to work on some openid connect server and would like to implement the session management draft that allows us to make a logout on the openid server and redirect us to a page pass in paramters.

I think most of the code is already there to support this new endpoint. I read that some people were using some trick by passing the prompt login to show again the login screen but this doesn't really clean all the token for that user. Implementing the session logout allows the provider to clean all the session informations in one call

I can try to help for this implementation if needed and if you think it's fine to add it as well. I just have windows to test tho :x

Here is the doc about it: https://openid.net/specs/openid-connect-session-1_0.html#RPLogout

**Comment by kadikraman** [comment]
Hi @DarkSorrow 👋 

It's definitely a desired feature. The reason we haven't implemented it is because the underlying libraries (AppAuth-iOS and AppAuth-Android) did not have support. As of right now,

- **AppAuth-iOS** have [merged support for single sign out](https://github.com/openid/AppAuth-iOS/pull/259/files)
- **AppAuth-Android** do not have support at the moment. There's open issues, but the library does not currently have an active maintainer, so the timeline is uncertain.

So currently we could implement it for iOS only which is not ideal, but would be a step in the right direction.

The main issue for it is [here](https://github.com/FormidableLabs/react-native-app-auth/issues/68) - let's keep the discussion in #68

**Comment by rashidul0405** [comment]
@kadikraman AppAuth-Android support has landed in Jan: https://github.com/openid/AppAuth-Android/pull/525
