### ISSUE TITLE
Better error handling for canceled auth flow

### ISSUE THREAD

**Issue by PeterKottas** [FormidableLabs/react-native-app-auth#46]
Report type:
BUG

Steps to reproduce:
Start current example app. 
Click authorize.
Not abandon authorization (click back)
Observe the red screen of death.

Expected result:
Exception should be thrown, catched and handled via user code. The code in example app indeed is surrounded with try catch block but it appears it's no use for this scenario.

Actual result:
App shows red screen of death 
![canceledauthflow](https://user-images.githubusercontent.com/10601911/36355353-2870e62c-14e2-11e8-8501-c2f7b9dcab4e.jpg)

**Comment by kadikraman** [comment]
@PeterKottas that's because the example app uses `console.error` to show you the error rather than `console.log`. Replace it with `console.log` and it will fail silently. This was intentional to draw the user's attention to something going wrong. It will only happen during development.

I do agree that the red screen of death can be a bit distressful so we could draw the user's attention to the errors with an Alert instead. 😄

**Comment by PeterKottas** [comment]
Damn you're absolutely right! Sorry for false alarm, I just saw red screen and figured all hell broke lose :D Still new to native, you learn every day, thanks!
