### ISSUE TITLE
[Android] Error `Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference` when call authorize

### ISSUE THREAD

**Issue by charitynguyenvan** [FormidableLabs/react-native-app-auth#473]
## Issue

---
```js
const f = async() => {
  try {
    const ret = await authorize(config)
    console.log(ret)
   } catch (error) {
     console.log('Failed to log in', error.message)
   }
 }
 f()
```

Error `Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference` when call `authorize(config)`

## Environment

* **Your Identity Provider**:  It works with iOS, but not Android
* **Platform that you're experiencing the issue on**: `only Android `
* **Are you using Expo?** No

**Comment by aeirola** [comment]
This seems to be an issue caused by #470 in [v5.1.0](https://github.com/FormidableLabs/react-native-app-auth/releases/tag/v5.1.0) when the `issuer` field is absent.

Quick fixes would be to either add the `issuer` field in the config, or to revert back to 5.0.2.

I'll see if I can get a PR for a proper fix.

**Comment by charitynguyenvan** [comment]
My bad when I didn't check `yarn.lock` file of the Example project and my new project.

I just checked `package.json` only.

I tried the Example just few days before v5.1.0 released.

Thanks for your perfect reply!
