### ISSUE TITLE
[Android] App crash on prefetchConfiguration if issuer is missing.

### ISSUE THREAD

**Issue by aeirola** [FormidableLabs/react-native-app-auth#478]
## Issue

Calling `prefetchConfiguration` on android with an authentication configuration that doesn't include the `issuer` field crashes the app. It doesn't just reject the async call, but uncontrollably just crashes the whole application.

`adb logcat` provides the following error output

```
03-02 08:04:45.387  7241  7241 E AndroidRuntime: FATAL EXCEPTION: main
03-02 08:04:45.387  7241  7241 E AndroidRuntime: Process: id.application.my, PID: 7241
03-02 08:04:45.387  7241  7241 E AndroidRuntime: java.lang.NullPointerException: uriString
03-02 08:04:45.387  7241  7241 E AndroidRuntime: 	at android.net.Uri$StringUri.<init>(Uri.java:490)
03-02 08:04:45.387  7241  7241 E AndroidRuntime: 	at android.net.Uri$StringUri.<init>(Uri.java:480)
03-02 08:04:45.387  7241  7241 E AndroidRuntime: 	at android.net.Uri.parse(Uri.java:452)
03-02 08:04:45.387  7241  7241 E AndroidRuntime: 	at com.rnappauth.RNAppAuthModule$8.onCustomTabsServiceConnected(RNAppAuthModule.java:765)
03-02 08:04:45.387  7241  7241 E AndroidRuntime: 	at androidx.browser.customtabs.CustomTabsServiceConnection.onServiceConnected(CustomTabsServiceConnection.java:57)
03-02 08:04:45.387  7241  7241 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1730)
03-02 08:04:45.387  7241  7241 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1762)
03-02 08:04:45.387  7241  7241 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
03-02 08:04:45.387  7241  7241 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-02 08:04:45.387  7241  7241 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
03-02 08:04:45.387  7241  7241 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
03-02 08:04:45.387  7241  7241 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-02 08:04:45.387  7241  7241 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-02 08:04:45.387  7241  7241 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

---

## Environment

* **Your Identity Provider**: `Auth0`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** `No`

**Comment by hauhuynh1208** [comment]
+1

**Comment by hauhuynh1208** [comment]
@aeirola Any updates?

**Comment by eisodev** [comment]
If anyone googles the above error, this was my mistake (TLDR check last sentence):

`
import Config from 'react-native-config';
...

export const identityConfig: AuthConfiguration = {
    issuer: Config.ID_SERVER_HOST, // this is now undefined, property ID_SERVER_HOST is set in .env file
   ...
`

Upgrading React Native from 0.69.12 - 0.73.7 and also upgraded react-native-config from ^1.4.6 to ^1.5.1.
And now my ID_SERVER_HOST is undefined.

running my script with npm run android:
`"android": "react-native run-android --terminal terminal",`

The reason was in the upgrade helper I by accident removed a crucial [block of code for react-native-config](https://github.com/lugg/react-native-config#extra-step-for-android:~:text=Alternatively%2C%20you%20can%20define%20a%20map%20in%20build.gradle%20associating%20builds%20with%20env%20files.%20Do%20it%20before%20the%20apply%20from%20call%2C%20and%20use%20build%20cases%20in%20lowercase%2C%20like%3A) in android/app/build.gradle
