### ISSUE TITLE
OAuth with Imgur on iOS

### ISSUE THREAD

**Issue by alexandra-picot** [FormidableLabs/react-native-app-auth#516]
## Issue

Hello,

I seem to be unable to interact with Imgur on iOS, every time the browser open to ask access, I get this error:

> ...{"error": "redirect_uri_mismatch", "request": "oauth2/authorize", "method": "GET"}...

First thing I thought (obviously) is that the callback url I registered on Imgur and the one in my app differs, it appears they are exactly the same, I double checked, and of the form:
`myapp://oauth`

I am unsure wether it comes from my config object, Imgur or this library as the exact same code works perfectly on Android (I do need to give my client secret for it to work though, otherwise I get an error after I allow the app to access my account).

Also I dare say it probably doesn't come from my installation as the exact same code with a reddit configuration object works perfectly on both iOS and Android (Without my client secret).

I am able to provide a very simple demo app if needed, or at least the problematic code.

I thank you in advance for your help.
Also sorry if I missed some needed details, I'm not used to open issues, I'll gladly provide anything needed to investigate this issue.

---

## Environment

* **Your Identity Provider**:  Imgur
* **Platform that you're experiencing the issue on**: tested on iOS 13.4, iOS 13.5
* **Are you using Expo?** No

**Comment by kadikraman** [comment]
I don't think you're doing anything wrong, I can confirm this doesn't work as expected, although I'd need to investigate further to pinpoint where exactly the issue is.

![Screenshot 2020-07-07 at 18 49 19](https://user-images.githubusercontent.com/6534400/86821687-9bc6cd00-c082-11ea-9976-b6395af140d6.png)

**Comment by StarryFire** [comment]
Any update on this? Did you solve the problem? I am facing the same problem for Google sign in.

RN v0.62
react-native-app-auth v5.1.2

**Comment by faizplus** [comment]
Imgur have issues with your redirectUrl `myapp://oauth`, you must wrap it with `encodeURIComponent` in order to make it work.

This is how the Imgur account can be configured correctly.
## Overview
1. Sign in to your [imgur account](https://imgur.com/) (step 1)
2. Create a new application (step 2)
3. Grab your credentials (steps 3)

## Step by step
**Step 1.** [Sign in to your imgur account](https://imgur.com/). Imgur use the same account for their main website, as well as the developers portal.
![image](https://github.com/FormidableLabs/react-native-app-auth/assets/10779658/64c3856e-dee7-4d24-bfa1-d01a59f47984)

**Step 2.** Once signed in, open the [OAuth application registration form](https://api.imgur.com/oauth2/addclient). From there:

- enter your Application name
- confirm that the Authorization type is OAuth2 authorization with a callback URL (default option)
- register a redirect URL to handle the OAuth dance. Use redirect schema like `com.myapp://oauth/callback`
- provide an email

![image](https://github.com/FormidableLabs/react-native-app-auth/assets/10779658/0b408fd2-4f98-4618-92cb-5d554aa29c63)

**Step 3.** Click save and that's it! Imgur will prompt your API keys right away.
![image](https://github.com/FormidableLabs/react-native-app-auth/assets/10779658/6adc9021-b58b-4126-9bc4-8f848b07ecfc)

💡 If ever you need to find your credentials again, they are accessible from [your account settings](https://imgur.com/account/settings/apps).

```javascript
// your configuration should look something like this
const config = {
  issuer: 'https://api.imgur.com/oauth2/',
  clientId: 'abc79a5abcdb30e', // your client id
  redirectUrl: encodeURIComponent('com.myapp://oauth/callback'), // must wrap it in encodeURIComponent 
  serviceConfiguration: {
    authorizationEndpoint: 'https://api.imgur.com/oauth2/authorize',
    tokenEndpoint: 'https://api.imgur.com/oauth2/token',
  },
};
```

After following every step correctly, you should be able to see the imgur login page.

![image](https://github.com/FormidableLabs/react-native-app-auth/assets/10779658/e39a400d-b525-4c1f-8749-d43c37290ffd)
