### ISSUE TITLE
Create specific error code to the cancellation of the oauth flow in both platform

### ISSUE THREAD

**Issue by roni-castro** [FormidableLabs/react-native-app-auth#565]
Isn't there a `authentication_canceled`  code to detect when the user closes the webview or cancel the alert (in iOS)?
Currently everytime the user does these actions an error is thrown, and one of the solutions can be the following, but it is not a good solution:

```
if (error === 'User cancelled flow' ||
    error === 'The operation couldn’t be completed. (org.openid.appauth.general error -3.)') { 
   // do not show error message and ignore this error
}
```

---

Simulation of the errors:

 When the user cancel the permission
<img width="416" alt="Captura de Tela 2020-09-30 às 11 12 35" src="https://user-images.githubusercontent.com/24610813/94696984-09933580-030e-11eb-82fc-da56b40938ff.png">

* This action generates `authentication_failed` error.code and the message `The operation couldn’t be completed. (org.openid.appauth.general error -3.)`
* This alert is not shown in Android

 When the user closes the webview
<img width="204" alt="Captura de Tela 2020-09-30 às 11 12 54" src="https://user-images.githubusercontent.com/24610813/94696994-0c8e2600-030e-11eb-9544-ff3f34e9ce98.png">

* This action generates **`authentication_failed`** error.code and the message `The operation couldn’t be completed. (org.openid.appauth.general error -3.)`
* This action generates **`authentication_error`** error.code and the message  `User cancelled flow` in Android

Related to this one: https://github.com/FormidableLabs/react-native-app-auth/issues/454

**Comment by Jay-A-McBee** [comment]
👋  hey @roni-castro - these error messages do include a code. For the iOS error (The operation couldn’t be completed. (org.openid.appauth.general error -3.)) - [the `-3 ` code represents "user cancelled flow"](https://github.com/openid/AppAuth-iOS/blob/e191b1beadf3041259652e6e464eaceff16e5fbb/Source/AppAuthCore/OIDError.h#L103). 

On Android the message itself can serve as the code. There is a numeric code associated with the "user cancelled flow" error (1).

<img width="500" alt="Screen Shot 2022-02-11 at 12 25 30 PM" src="https://user-images.githubusercontent.com/13589602/153665754-e61c2fdd-5099-4b3d-b177-f2556a867286.png">

But, because the message is so explicit, I'm not sure we need to return the code.  I think you'd be fine in this instance to use a regex to test the error message string or some other matching mechanism for both platforms - `/user cancelled flow|error -3/i`.

Closing this out.

**Comment by kabirbaidhya** [comment]
It would be nice to document this in the README because this is a pretty common use-case to understand whether the user cancelled the flow or it failed due to an error.
