### ISSUE TITLE
Authenticating with GitHub

### ISSUE THREAD

**Issue by alizahid** [FormidableLabs/react-native-app-auth#58]
Here's my config

```
{
  serviceConfiguration: {
    authorizationEndpoint: 'https://github.com/login/oauth/authorize',
    tokenEndpoint: 'https://github.com/login/oauth/access_token'
  },
  clientId: '',
  clientSecret: '',
  redirectUrl: 'github://oauth',
  scopes: ['gist']
}
```

When I call `authorize`, the GitHub login page opens, and once I click `Authorize`,  it comes back to the app, and throws the following error

```
The operation couldn’t be completed. (org.openid.appauth.general error -7.)

<unknown>
    NativeModules.js:80:32
MessageQueue.__invokeCallback
    MessageQueue.js:400:4
<unknown>
    MessageQueue.js:139:11
MessageQueue.__guardSafe
    MessageQueue.js:316:6
MessageQueue.invokeCallbackAndReturnFlushedQueue
    MessageQueue.js:138:9
<unknown>
    debuggerWorker.js:72:58
```

What does that error mean? Doesn't give me much to go on.

Is it a config issue? Or something to do with `redirectUrl`?

**Comment by alizahid** [comment]
Another observation: Even if I press cancel on the dialog that shows up asking to continue or cancel when I call `authorize`, it throws the same error. Except it's error `-3`.

**Comment by alizahid** [comment]
After further debugging, turns out GitHub doesn't send the response in JSON by default. Which is what's throwing off AppAuth. How do I pass the `Accept` header with `application/json` to make sure it sends back appropriate response?

**Comment by jevakallio** [comment]
@alizahid can you point out to documentation/issues/resources that describes how the GitHub API behaves? Sounds *really* weird that they would not respond with a JSON payload - what do they send instead?

Also, can you please confirm that you're using react-native-app-auth version 2.2.0 or newer? The support for `serviceConfiguration` just landed yesterday afternoon, so if you had installed this before that, you might not be on the latest.

**Comment by alizahid** [comment]
Here's the documentation link for GitHub OAuth https://developer.github.com/apps/building-oauth-apps/authorization-options-for-oauth-apps/#response

By default, they send this

```
access_token=e72e16c7e42f292c6912e7710c838347ae178b4a&token_type=bearer
```

I modified some code in `AppAuth-iOS`, so it sends the `Accept` header with `application/json`, and I was able to move past the JSON parse error. But it seems that GitHub doesn't expire tokens, and thus, didn't send a `expires_at` value in the payload, which threw another exception. Something about `NSDate` can't parse from `nil` or something. I can't remember the exact exception.

I am on `2.2.1`. You're correct, when I created this issue, `2.2.0` hadn't landed yet. But the documentation was updated. So my first issue was that it kept asking for `issuer`, and then I saw the update, so I updated.

**Comment by kadikraman** [comment]
@alizahid great investigation 🤓

You're right on both accounts. I've made a PR to fix the Android date parsing -  https://github.com/FormidableLabs/react-native-app-auth/pull/61 

Looks like the Android library sets an accept header which is why it works following the date parsing fix, however iOS does not. They've actually included a comment to say they've set the header due to [GitHub defaulting to sending the response in xml](https://github.com/openid/AppAuth-Android/blob/619e9b0f6d27fd393a8332ceb324d8d243082251/library/java/net/openid/appauth/AuthorizationService.java#L505) 😄 

So we'll just need to do a PR to [AppAuth-iOS](https://github.com/openid/AppAuth-iOS) to add it there as well.

**Comment by alizahid** [comment]
I've tested only with iOS, though.

Interesting that they have the GitHub behavior for Android, but not iOS. And I didn't see any mention of XML in GitHub documentation.

I've been looking into an alternative solution with `WebView` and `fetch`. But will switch back as soon as the PRs are merged. Thanks!

**Comment by kadikraman** [comment]
Ah yes, iOS had the same date formatting issue. I'd actually fixed it locally, but forgot to make a PR 🙈  - will do so now.

**Comment by jevakallio** [comment]
Just dropping a link to the AppAuth-iOS PR so it's easier to track when it's merged https://github.com/openid/AppAuth-iOS/pull/206

**Comment by kadikraman** [comment]
Sorry to announce that this will be a `won't-fix` for us for iOS.

The [AppAuth-iOS](https://github.com/openid/AppAuth-ios) maintainers will not include the Accept header, because although it does not change the behaviour of other providers, it is not strictly in the OAuth spec so could be a slippery slope. Can't argue with that.

They do plan to extend the library to potentially enable setting custom headers, but these things take time, so I wouldn't hold my breath.

As suggested in the PR, a potential workaround would be to use a fork of the library that adds the header. (Or get GitHub to change their non-OAuth compliant ways - ha!) But realistically, we just won't be able to support GitHub login on iOS until further notice.

Read the discussion on the PR for more details: https://github.com/openid/AppAuth-iOS/pull/206
