### ISSUE TITLE
Ebay Authentication

### ISSUE THREAD

**Issue by damithg-dev** [FormidableLabs/react-native-app-auth#631]
So I tried to use eBay authentication, but I was facing an issue due to eBay limitation. They are only supporting the redirect HTTPS, Have to use the redirect URL id they provide. So I'm not sure how to resolve this. I need help to achieve this.  

[This answer will explain how it works](https://stackoverflow.com/a/45330860/6668308)

I was able to get authenticated but redirection won't work due to redirect URL id.

**Comment by Jay-A-McBee** [comment]
:wave: hey. @damithg-dev - I don't think you'll be able to use this library to integrate ebay OAuth. There is a check within the native backing libraries that will compare the `redirectUrl` passed on the config object to the incoming url from the idP. [iOS code ](https://github.com/openid/AppAuth-iOS/blob/e191b1beadf3041259652e6e464eaceff16e5fbb/Source/AppAuthCore/OIDAuthorizationService.m#L170) - the same check exists in the Android version.

In your case (or the ebay case) this will always return false because the config object `redirectUrl` will be the RU name that ebay requires while the incoming url will be the actual https url you've configured on the ebay app console.

I'll leave this open for a few days so please chime in if my thinking about this incorrect.
