### ISSUE TITLE
Close view when arbitrary URL is reached (during registration)

### ISSUE THREAD

**Issue by pke** [FormidableLabs/react-native-app-auth#636]
I am not sure its the correct way but we are also using this package to show the user registration flow on an OIDC Server.
However at the end of the registration process the server shows a "you need to activate" your email now and this page stays visible. We would like to close the auth view at this stage and display the message in the app rather and wait for the user to activate the account.

Does RN-App-Auth support this kind of scenario or should we use a normal secure web view (expo?) which allows us to close the view when a certain URL is hit inside the browser view?

**Comment by Jay-A-McBee** [comment]
The initial login request is waiting for the configured `redirectUrl` to get called. This would trigger the close of the webview. Your client registration service would need to redirect to this url upon successfully registering a client. This will result in an error though because it deviates from the expected flow of the app auth libraries. 

I would suggest splitting these into a separate view/services - have separate links for login and sign up in the App view. 

Closing this out as it's not an issue with the library.
