### ISSUE TITLE
Auto property synthesis warning on build in XCode

### ISSUE THREAD

**Issue by martsie** [FormidableLabs/react-native-app-auth#662]
## Issue

When building in XCode we get the error `Auto property synthesis will not synthesize property 'authorizationFlowManagerDelegate' declared in protocol 'RNAppAuthAuthorizationFlowManager'` with a fix option. The fix adds `@synthesize authorizationFlowManagerDelegate;` underneath `@implementation AppDelegate` . Is this something we need to do or is this warning a false one?

<img width="702" alt="CleanShot 2021-08-17 at 10 20 17@2x" src="https://user-images.githubusercontent.com/11308291/129644923-5e6d1007-debc-4293-9dd2-ebc2e4186edc.png">

---

## Environment

* **Your Identity Provider**: `N/A`
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?** NO

**Comment by Jay-A-McBee** [comment]
:wave: hey @martsie  - sorry it took so long to respond 😸 - So I had to do some research to figure out what the @synthesize directive does 🔎  and I actually had to turn these warnings on in xcode to reproduce this. You probably already know, but the C compiler is warning you here, "Hey because this property comes from a protocol, I'm not going to auto generate a getter and setter for this property." 

This isn't an issue because we do provide a custom setter of sorts for this property in both the [authorize](https://github.com/FormidableLabs/react-native-app-auth/blob/main/ios/RNAppAuth.m#L345) and end session methods . Also if you need to access this property you must use `self` - this is illustrated in the "[Define openURL callback in AppDelegate section](https://github.com/FormidableLabs/react-native-app-auth#define-openurl-callback-in-appdelegate)"  of the README - see the last two code snippets.

Haha so long story short, nothing to worry about here!
