### ISSUE TITLE
Feature request: Non react-native version

### ISSUE THREAD

**Issue by SrMouraSilva** [FormidableLabs/react-native-app-auth#707]
There is any plans to develop a ReactJs (non react-native) version?

**Comment by Jay-A-McBee** [comment]
:wave: morning @SrMouraSilva 

Hmm... 🤔  - I don't think there's been any discussion around building out another wrapper for the AppAuth libraries. Our current wrapper seems warranted because integrating AppAuth-ios/Android into an RN app is not something every React/React-Native dev is familiar with. The learning curve is pretty steep - I'm constantly having to reference obj-c and Android/Java documentation when I'm working on/reading through the native modules.

There is a JS version ([AppAuth-JS](https://github.com/openid/AppAuth-JS)) of the native library this package (react-native-app-auth) uses. The learning curve there for a React dev is not steep because they integrate JS libs all the time. I don't know if an additional JS wrapper around AppAuth-JS is warranted 🤷‍♂️ .

**Comment by SrMouraSilva** [comment]
Hello, @Jay-A-McBee.

I agree with your points. In fact there are a lot of js/react implementations, but they're missing implementation something and some decisions of them are strange for my opinion, that's why I questioned if there was an implementation (because I love this project and know the quality of them).

I will continue my search 😊
