### ISSUE TITLE
Gets redirect back to login on successful login

### ISSUE THREAD

**Issue by Nirodha26** [FormidableLabs/react-native-app-auth#708]
## Issue
On calling authorize method it gets navigated to redirect url but once successfully logged in, it's navigated to redirect url again (opening a tab) instead of navigating back to the app. This was reproducible in Galaxy S6 Android 7.0 device only.

---

## Environment

* **Your Identity Provider**: `IdentityServer4`
* **Platform that you're experiencing the issue on**: `Android`
* **Are you using Expo?** `No`

**Comment by Jay-A-McBee** [comment]
:wave: hey @Nirodha26 - Which browser is opened in the custom tab? Is it the default Samsung "Internet" browser? If so, I found [an old issue](https://github.com/openid/AppAuth-Android/issues/116) in AppAuth-Android that sounds similar.

Adding functionality to specify the browser for the custom tab is something we want to add, and there's already an associated PR (It set around for a while and has conflicts now 🤷‍♂️ ). I think you've got an active fork of the lib right now so you might be able to work this in there before we can.

**Comment by Nirodha26** [comment]
@Jay-A-McBee Hello 👋  Thanks for the quick response.

Custom tab is opened with Chrome which is set as the default browser in the device. So it seems the mentioned issue is not related to this.

However we tried following two steps,

1. Clear data, cache on default browser and try logging in again
2. Clear data, cache on V2 app and try logging in again

While 1st step didn't resolve the issue 2nd step did. Any idea why?

**Comment by Jay-A-McBee** [comment]
hmm... I'm not sure why clearing the app's cache would cause the failed redirect to suddenly work 🤔 . Was the auth flow the same or did you have to log in to the provider again? Also what's the structure of your redirect url - custom protocol or `https` ?

If you could provide a short screencast of the failed flow and the working flow that would be helpful. Because this is device specific and on an older Android version, I'm leaning toward this not being an issue in the library. Happy to help debug though 👍

**Comment by Jay-A-McBee** [comment]
No response - closing this out.
