### ISSUE TITLE
Ios authorize returns wrong authorization code

### ISSUE THREAD

**Issue by HarshavardhanRai** [FormidableLabs/react-native-app-auth#712]
## Issue

I have been trying to login the app with the react native app auth, it works fine in android .
In ios it opens the browser and and will be able to enter the username and passowrd and upon click on login, it will return back but returns the wrong authorization code which will msimatch with the identity server code. Please help in resolving the issue.
---

## Environment
Im using latest version of reactnative app auth.
* **Your Identity Provider**: `Azure`
* **Platform that you're experiencing the issue on**: `iOS`
* **Are you using Expo?** No

My react-native version is: "0.63.2"
react-native-app-auth: "6.4.3"

**Comment by Jay-A-McBee** [comment]
:wave: hey @HarshavardhanRai - hmm... I did some testing last week with our example app using Azure AD as my provider and I did not see this issue.  We have had [issues](https://github.com/FormidableLabs/react-native-app-auth/pull/593) in the past with a missing trailing slash on the `redirectUrl` property. Make sure that the redirect url you pass to the authorize method ends with `/`.


I successfully logged in with Azure using this config:
```
{
  issuer:
      'https://login.microsoftonline.com/<TENANT-ID>/v2.0/',
    clientId: <CLIENT ID>,
    redirectUrl: 'example.myapp.com://oauth/',
    scopes: [ 'openid', 'offline_access']
}
```

I have also been able to successfully login using Azure AD B2C with the following config: 
```
issuer:
      'https://rnappauthdemo.b2clogin.com/rnappauthdemo.onmicrosoft.com/B2C_1_up_in/v2.0/',
    clientId: <APP_ID>,
    redirectUrl: 'msauth.org.reactjs.native.example.Example://auth/',
    scopes: [
      'openid',
      'offline_access',
      <APP_ID>,
    ]
```
Note that I included the app id in the scope's array for the B2C config - [MSFT documentation](https://docs.microsoft.com/en-us/azure/active-directory-b2c/access-tokens#openid-connect-scopes).

Let me know if this helps :rocket:

**Comment by HarshavardhanRai** [comment]
Hi @Jay-A-McBee : I have tried with with redirect url with "/" but it gives invalid request and also can you please let me know what are the configuration i need to do in ios for react-native-app-auth.

**Comment by Jay-A-McBee** [comment]
@HarshavardhanRai - there are a couple of changes you need to make for iOS. You need to [register your redirect url](https://github.com/FormidableLabs/react-native-app-auth#register-redirect-url-scheme) (info.plist change) and you also need to make [changes to the AppDelegate](https://github.com/FormidableLabs/react-native-app-auth#define-openurl-callback-in-appdelegate) in order for it to conform to the `RNAppAuthAuthorizationFlowManager` protocol. I assume you have already made the necessary changes to `AppDelegate.h` otherwise the `authorization` method would throw an error.

**Comment by HarshavardhanRai** [comment]
@Jay-A-McBee 
I have added necessary configurations in info.plist and AppDelegate.h
The issue still persists, I'm still receiving the wrong code.
here are my configurations.
```
config = {
  issuer: '<issuer_name>',
  clientId: 'react',
  redirectUrl: '<app_name>:/oauthredirect/',
  scopes: ['openid', 'profile', 'email', 'offline_access', 'default.manage'],
  additionalParameters: { display: '' },
  skipCodeExchange: true,
}; 
```

info.plist

```
<key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLName</key>
      <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
      <key>CFBundleURLSchemes</key>
      <array>
        <string><app_name></string>
      </array>
    </dict>
  </array>
```

AppDeligate.h

```
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>
#import "RNAppAuthAuthorizationFlowManager.h"

@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate, RNAppAuthAuthorizationFlowManager>
//@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate>
@property(nonatomic, weak)id<RNAppAuthAuthorizationFlowManagerDelegate>authorizationFlowManagerDelegate;
@property (nonatomic, strong) UIWindow *window;

@end
```

AppDeligate.m

```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>     
#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>


static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate


 
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *, id> *) options {
 if ([self.authorizationFlowManagerDelegate resumeExternalUserAgentFlowWithURL:url]) {
    return YES;
  }
  return [RCTLinkingManager application:app openURL:url options:options];
 }

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions

{
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"LisAuthenticator"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}



@end

```

**Comment by Jay-A-McBee** [comment]
@HarshavardhanRai - I notice you have `skipCodeExchange: true` in your config. Are you manually exchanging the returned `code` for an access token through a backend service? If so, your server would be responsible for [this request](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-access-token-with-a-client_secret) in the auth flow. Note the `code_verifier` property in the request.
<img width="687" alt="Screen Shot 2022-02-23 at 10 26 57 AM" src="https://user-images.githubusercontent.com/13589602/155383754-8f23aed4-7585-4043-8fd4-5842747bf11f.png">

`usePKCE` has a default value of `true` for the `authorize` [request ](https://github.com/FormidableLabs/react-native-app-auth/blob/main/index.js#L202) meaning a `code_verifier` property is included in the initial authorize request.  Since, based on your config, it looks like you are handling the code/token exchange request manually, your backend service would need to provide the same `code_verifier` used in the authorize request to successfully complete the code/access_token exchange request. Simply put your backend won't have access to the original `code_verifier` so I don't think this will be possible. 

Although, I don't understand how the same config and auth flow is working on Android 🤔 . 

`PKCE` is recommended and would be required if you were carrying out the entire authorization code grant flow client side. But, you are exchanging the code for an access token server side so it isn't necessarily required.  A `PKCE` implementation provides an added layer of security for public clients that cannot store a `client_secret` securely - native apps, etc. Your server on the other hand can securely store your `client_secret` and include it when making the code/access_token exchange request.  

If your server is handling the code exchange, try setting `usePKCE: false` on your config. Again, I'm not sure why this would work on Android and not iOS.

**Comment by karlika** [comment]
@Jay-A-McBee 
I'm a colleague of @HarshavardhanRai, responsible for the server side implementation of the flow. Turns out that on Android side this is only working, because there we did a modification to the library to be able to pass our own code challenge which is generated on server side in the first step of the flow. This was apparently never pushed (the colleague who came up with this left the company, so can't ask him for details)

Maybe you could point out if and what we are doing wrong, or how we could achieve handling of PKCE on server side without passing the callenge to the frontend for the first step?

**Comment by karlika** [comment]
@Jay-A-McBee 
Just some info on the workflow we are using (or are trying to):
1. We call our server to get the client_id, authentication endpoint and also the code_verifier
2. The app then calls authorize with those parameters
3. Passing back the code to our server
4. Server calls the token endpoint with the code and challenge and returns the obtained token

How else would we do this workflow without passing the client secret to the app?

**Comment by Jay-A-McBee** [comment]
:wave: morning @karlika -  I was suggesting that you drop the `code_verifier` and `challenge` from step 2 by setting `usePKCE: false` on the authorize request. The risk in not using PKCE is that the code could be intercepted by a malicious app installed on the user's device, but this is only an actual risk if your `client_secret` is in your app's provisioned binary. This comes from the [PKCE RFC](https://datatracker.ietf.org/doc/html/rfc7636#section-1).

<img width="526" alt="PKCE_RFC" src="https://user-images.githubusercontent.com/13589602/156219530-61526b9b-3f5e-4c58-b195-222de7c3a264.png">

Because you are handling the code/token exchange server side, I'm assuming your `client_secrect` isn't hard-coded into your app's binary and that you can securely store the `client_secret` on your server. You would use this value when making the code/token exchange request instead of the PKCE params (code_verifier/challenge). If a malicious app managed to intercept the `code` during the authorize redirect, it would still need access to your client secret to exchange this for an access token. Storing the `client_secret` on your server and handling the code/token exchange in that environment thoroughly mitigates this risk.

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out.
