### ISSUE TITLE
Attempt to invoke virtual method 'android.net.Uri$Builder android.net.Uri.buildUpon()' on a null object reference when calling logout

### ISSUE THREAD

**Issue by hardiksonagrav** [FormidableLabs/react-native-app-auth#714]
## Issue

    const config = {
          issuer: 'ISSUER',
        };

    const result = logout(config, {
      idToken: 'TOKEN',
      postLogoutRedirectUrl: '<POST_LOGOUT_URL>',
    });

Attempt to invoke virtual method 'android.net.Uri$Builder android.net.Uri.buildUpon()' on a null object reference when calling logout.

---

## Environment

* **Your Identity Provider**: 
* **Platform that you're experiencing the issue on**: `both`
* **Are you using Expo?** No

**Comment by Jay-A-McBee** [comment]
:wave: hey @hardiksonagrav  - hmm... I tracked down a couple places where the `Uri.buildUpon` method is called and I think the service configuration returned from the `<ISSUER>/.well-known/openid-configuration` endpoint is most likely the problem. 

This library calls `Uri.buildUpon` in a [single place](https://github.com/FormidableLabs/react-native-app-auth/blob/580372daf92fab88f645b12b3ba3d9cf0f219fe8/android/src/main/java/com/rnappauth/RNAppAuthModule.java#L933).  It is invoked on the parsed `issuer` uri which you clearly have in your config. I can't know for sure without seeing the error's full stack trace, but I don't think this call is responsible for the error.

I'm guessing the error is thrown in the native library AppAuth-Android. The offending line is [here](https://github.com/openid/AppAuth-Android/blob/90f22331603822734141af6c543ead74ef0cafd0/library/java/net/openid/appauth/AuthorizationService.java#L558) which triggers [this method](https://github.com/openid/AppAuth-Android/blob/0939d6d42e727dd60b044ecd443bc752af9fd72a/library/java/net/openid/appauth/EndSessionRequest.java#L275) in the `EndSessionRequest` class.

Note that `buildUpon` is being called on `configuration.endSessionEndpoint`. Since your config only has an `issuer` and not an explicit `serviceConfiguration`, the service configuration is first fetched from the `<ISSUER>/.well-known/openid-configuration` endpoint. I'm assuming the returned config does not have an `endSessionEndpoint` property. 

You should be able to confirm this relatively easily by hitting that endpoint in your browser.

Let me know if that ends up being the issue 🚀

**Comment by Jay-A-McBee** [comment]
No response from OP - closing this out

**Comment by juanm4** [comment]
Hi @Jay-A-McBee, I'm experiencing the same error when I try to logout on Android. On iOS is working fine. 
Hi have checked `<ISSUER>/.well-known/openid-configuration` and the property called `end_session_endpoint ` is present and is correct.

So, why does it still failing? I don't understand why it works on iOS but not in Android. Maybe I'm missing something...

Thanks in advance!

**Comment by nidhipate124** [comment]
I'm also facing the same issue, does anyone find a solution to this? @hardiksonagrav @Jay-A-McBee @juanm4

**Comment by farmaker47** [comment]
![image](https://github.com/FormidableLabs/react-native-app-auth/assets/26084498/72f58aaa-59e4-4c37-b980-fea1619b951f)

It throws null because at below code:

```
@Override
    public Uri toUri() {
        Uri.Builder uriBuilder = configuration.endSessionEndpoint.buildUpon();

        UriUtil.appendQueryParameterIfNotNull(uriBuilder, PARAM_ID_TOKEN_HINT, idTokenHint);
        UriUtil.appendQueryParameterIfNotNull(uriBuilder, PARAM_STATE, state);
        UriUtil.appendQueryParameterIfNotNull(uriBuilder, PARAM_UI_LOCALES, uiLocales);

        if (postLogoutRedirectUri != null) {
            uriBuilder.appendQueryParameter(PARAM_POST_LOGOUT_REDIRECT_URI,
                    postLogoutRedirectUri.toString());
        }

        for (Map.Entry<String, String> entry : additionalParameters.entrySet()) {
            uriBuilder.appendQueryParameter(entry.getKey(), entry.getValue());
        }

        return  uriBuilder.build();
    }
```

endSessionEndpoint is null. You can move forward by setting 4 endpoints when you create the 

```
val serviceConfiguration = AuthorizationServiceConfiguration(
            Uri.parse("https://example.authorization"), // Authorization Endpoint
            Uri.parse("https://example.token"), // Token Endpoint
            Uri.parse("https://example.registration"), // Registration endpoint
            Uri.parse("https://example.endsession")  // End session endpoint
        )
```
