### ISSUE TITLE
Logout - Popup message

### ISSUE THREAD

**Issue by houssemanypli** [FormidableLabs/react-native-app-auth#718]
Hello, I am using logout function and i am getting the exact message for authorize connection popup in IOS is there any solution for telling the user he is about to sign out instead? Thanks
<img width="158" alt="Screen Shot 2022-03-15 at 11 10 00 PM" src="https://user-images.githubusercontent.com/97892581/158480839-979a39a0-8512-483e-a76a-fc4b94d9ad7f.png">

**Comment by Jay-A-McBee** [comment]
:wave: hey @houssemanypli -  Unfortunately again this is a known issue on iOS and has come up as an [issue](https://github.com/FormidableLabs/react-native-app-auth/issues/706) in the past. This [issue](https://github.com/openid/AppAuth-iOS/issues/643) is linked in #706 and it mentions a config option `prefersEphemeralWebBrowserSession` as a potential way to sidestep the mis-worded system alert. 

From Apple developer docs:
> Set prefersEphemeralWebBrowserSession to true to request that the browser doesn’t share cookies or other browsing data between the authentication session and the user’s normal browser session. 

Because the auth session wouldn't share the auth cookie values with a standard browser session, the user would be forced to log in again even if they have already authenticated through the app. The inverse would also be true if a user authenticated through the app in a non-ephemeral browser session and then attempted to logout using an ephemeral browser session. The user would need to logout again from any standard browser sessions sharing the original auth cookie. If my thinking about this is correct, we'd be forced to set this for both the `authorize` and `logout` methods. It's unlikely that we would extend our `authorize` and `logout` methods to accept this configuration option as it produces a suboptimal authentication flow. Haha I promise one day I'll have good news 😸

**Comment by nios87** [comment]
@Jay-A-McBee  Hey. 

As i understand it the flow of opening a browser for auth is just fine even by Apple standards. What i dont get is the difference prefersEphemeralWebBrowserSession bring to the table and why that would cause the popup to not show.
Also why would it cause a suboptimal flow?

**Comment by Jay-A-McBee** [comment]
Closing this out - it's hard to justify adding this configuration option in response to a minor UI bug (imo).

**Comment by muhammadabbas001** [comment]
@Jay-A-McBee Suppose someone uses the prefersEphemeralWebBrowserSession and then the alert will not show, but the session will not remove from the browser by doing this. What I can do about this?
